version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "25432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
  app:
    build: ./app/
    restart: unless-stopped
    depends_on:
      - "db"
    ports:
      - "8080:8080"
  flask_app:
    build: ./flask_app/
    restart: unless-stopped
    depends_on:
      - "app"
    ports:
      - 9000:5000
